GET http://localhost:3003/students

###

POST http://localhost:3003/students
Content-Type: application/json

{
    "nome": "zxzxzx",
    "email": "zxzxzxzx@light.com",
    "data_nasc": "1996/02/06",
    "turma_id": "1",
    "hobby": ["magia"]
}

###
GET http://localhost:3003/students/students?nome=tio

###

POST http://localhost:3003/docente
Content-Type: application/json

{
    "id": "4",
    "nome": "teacherTest",
    "email": "pataaatdvadi@teacherTest.com",
    "data_nasc": "29/06/1992",
    "turma_id": "1",
    "especialidade": "JS"
}